name = "dove"
version = "0.6.0"

description = "Fast and flexible http client for Gleam"
gleam = ">= 0.32.0"
licences = ["Apache-2.0"]
links = [{title = "Gleam", href = "https://gleam.run"}]
repository = {type = "github", user = "massivefermion", repo = "dove"}
target = "erlang"

internal_modules = [
  "dove/tcp",
  "dove/client",
  "dove/request",
  "dove/response",
]

[dependencies]
gleam_erlang = "~> 0.23"
gleam_http = "~> 3.5"
gleam_json = "~> 0.7"
gleam_stdlib = "~> 0.32"
mug = "~> 0.2"

[dev-dependencies]
gleeunit = "~> 1.0"
